# Generated by Django 3.1.7 on 2021-06-01 10:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210420_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='avatars/default_pic.png', force_format=None, keep_meta=True, quality=100, size=[50, 64], upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
